[package]
name = "simple-rust-test"
version = "0.1.0"
authors = ["Hanna Reitz <hanna@xanclic.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
